### ISSUE TITLE
Margin Protocol WIP

### ISSUE THREAD

**Issue by xlc** [laminar-protocol/flow-protocol-ethereum#33]
- struct TradingPair

  - FlowToken base
  - FlowToken quote

- LiquidityPoolInterface

  - fn getBidSpread(address fToken): uint
  - fn getAskSpread(address fToken): uint

- SyntheticProtocolLiquidityPoolInterface: LiquidityPoolInterface

  - fn getAdditionalCollateralRatio(address fToken): uint
  - fn canMint(address fToken): bool

- MarginProtocolLiquidityPoolInterface: LiquidityPoolInterface

  - fn getSwapRate(address pair): uint
  - fn canOpenPosition(address pair, uint positionId, int leverage, uint leveraged_amount): bool

- MarginProtocolLiquidityPoolManager

  - mapping ((MarginProtocolLiquidityPoolInterface, TradingPair) => uint) accumaltedSwapRate
  - fn getAccumulatedSwapRate(TradingPair pair, MarginProtocolLiquidityPoolInterface pool): uint
  - 

- LiquidityPoolRegistry

  - mappings (LiquidityPoolInterface => address poolOwners)
  - LiquidityPools[] verifiedPools
  - fn register(LiquidityPoolInterface pool)
    - add to poolOwenrs
    - emit event
  - fn unregister(LiquidityPoolInterface pool)
    - remove from poolOwners
    - emit event
  - fn verify(LiquidityPoolInterface pool, address owner)
    - require contract owner
    - dd to verified pools
  - fn unverify(LiquidityPoolInterface pool, uint index)
    - require contract owner or pool owner
    - remove from verified pools

- FlowMarginProtocol

  - uint constant MARGIN_CALL_FEE
  - uint const LIQUIDATION_FEE
  - PriceOracleInterface oracle
  - ERC20 baseToken
  - mapping (address => uint) balances
  - 
  - fn open_position(MarginProtocolLiquidityPoolInterface pool, TradingPair pair, int leverage, uint leveraged_amount, price: uint): uint
    - `price` is the max (long) / min (short) acceptable trade price spread included
  - fn close_position(uint positionId, uint price)
  - fn trader_margin_call(address who)
    - Upon successful call, caller get `MARGIN_CALL_FEE` from trader
  - fn trader_become_safe(address who)
  - fn liquidity_pool_margin_call(MarginProtocolLiquidityPoolInterface pool)
  - fn liquidity_pool_become_safe(MarginProtocolLiquidityPoolInterface pool)
  - fn liquidity_pool_liquidate(MarginProtocolLiquidityPoolInterface pool)
    - Upon successful call, caller get `MARGIN_CALL_FEE` from liquidity pool
  - fn deposit(uint baseTokenAmount)
  - fn withdraw(uint baseTokenAmount)

**Comment by gorgos** [comment]
Pretty sure this is mostly done now. There are obviously things like a bit of clean up, documentation, cucumber test updates etc, but nothing major. Except for the optional #99.
