### ISSUE TITLE
Margin Protocol: User balances can become negative

### ISSUE THREAD

**Issue by gorgos** [laminar-protocol/flow-protocol-ethereum#62]
When user withdraws free margin, it could be more than his original deposit.

See https://github.com/laminar-protocol/laminar-chain/pull/156/ for the fix in Rust.

**Comment by xlc** [comment]
This is a nice to have feature.

**Comment by gorgos** [comment]
I think it's a must-have feature, because right now it would just cause a sub underflow. And just setting it to 0 instead would also cause issues in the future. We need to keep track of the proper user balance somehow.

**Comment by xlc** [comment]
we can just stop user from withdraw to below zero. that means they cannot withdraw all their unrealized profits, which is not a deal breaker.

**Comment by gorgos** [comment]
Okay, well that's basically what we have right now: a reverted transaction.
